require 'spec_helper'
require 'cancan/matchers'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::MessagesController do
  # http://www.michaelharrison.ws/weblog/?p=349
  include Devise::TestHelpers
  
  def mock_current_user(stubs={})
      @mock_current_user ||= mock_model(User, stubs).as_null_object
  end

  before(:each) do
      # mock up an authentication in the underlying warden library
      request.env['warden'] = mock(Warden, :authenticate => mock_current_user,
                                           :authenticate! => mock_current_user)
      setup_authorization
  end
  # endsnip
  
  def setup_authorization
    @ability = Object.new
    @ability.extend(CanCan::Ability)
    @controller.stub(:current_ability).and_return(@ability)
  end

  def mock_message(stubs={})
    @mock_message ||= mock_model(Message, stubs).as_null_object
  end

  describe "GET index" do
    describe "authorized as admin" do
      it "assigns all admin_messages as @admin_messages" do
        @ability.can :manage, :all
        Message.stub(:all) { [mock_message] }
        get :index
        assigns(:admin_messages).should eq([mock_message])
      end
    end
    
    describe "not authorized as admin" do
      it "does not assign all admin_messages as @admin_messages" do
        should_not be_able_to(:view, :index)
      end
    end
  end

  describe "GET show" do
    it "assigns the requested message as @message" do
      @ability.can :manage, :all
      Message.stub(:find).with("37") { mock_message }
      get :show, :id => "37"
      assigns(:admin_message).should be(mock_message)
    end
  end

  describe "GET new" do
    it "assigns a new message as @message" do
      @ability.can :manage, :all
      Message.stub(:new) { mock_message }
      get :new
      assigns(:admin_message).should be(mock_message)
    end
  end

  describe "GET edit" do
    it "assigns the requested message as @message" do
      @ability.can :manage, :all
      Message.stub(:find).with("37") { mock_message }
      get :edit, :id => "37"
      assigns(:admin_message).should be(mock_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created message as @message" do
        @ability.can :manage, :all
        Message.stub(:new).with({'these' => 'params'}) { mock_message(:save => true) }
        post :create, :message => {'these' => 'params'}
        assigns(:admin_message).should be(mock_message)
      end

      it "redirects to the created message" do
        @ability.can :manage, :all
        Message.stub(:new) { mock_message(:save => true) }
        post :create, :message => {}
        response.should redirect_to(admin_message_url(mock_message))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved message as @message" do
        @ability.can :manage, :all
        Message.stub(:new).with({'these' => 'params'}) { mock_message(:save => false) }
        post :create, :message => {'these' => 'params'}
        assigns(:admin_message).should be(mock_message)
      end

      it "re-renders the 'new' template" do
        @ability.can :manage, :all
        Message.stub(:new) { mock_message(:save => false) }
        post :create, :message => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested message" do
        @ability.can :manage, :all
        Message.stub(:find).with("37") { mock_message }
        mock_message.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :message => {'these' => 'params'}
      end

      it "assigns the requested message as @message" do
        @ability.can :manage, :all
        Message.stub(:find) { mock_message(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:admin_message).should be(mock_message)
      end

      it "redirects to the message" do
        @ability.can :manage, :all
        Message.stub(:find) { mock_message(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(admin_message_url(mock_message))
      end
    end

    describe "with invalid params" do
      it "assigns the message as @message" do
        @ability.can :manage, :all
        Message.stub(:find) { mock_message(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:admin_message).should be(mock_message)
      end

      it "re-renders the 'edit' template" do
        @ability.can :manage, :all
        Message.stub(:find) { mock_message(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested message" do
      @ability.can :manage, :all
      Message.stub(:find).with("37") { mock_message }
      mock_message.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the admin_messages list" do
      @ability.can :manage, :all
      Message.stub(:find) { mock_message }
      delete :destroy, :id => "1"
      response.should redirect_to(admin_messages_url)
    end
  end

end
