require 'spec_helper'
require 'cancan/matchers'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::UsersController do
  # http://www.michaelharrison.ws/weblog/?p=349
  include Devise::TestHelpers
  
  def mock_current_user(stubs={})
      @mock_current_user ||= mock_model(User, stubs).as_null_object
  end

  before(:each) do
      # mock up an authentication in the underlying warden library
      request.env['warden'] = mock(Warden, :authenticate => mock_current_user,
                                           :authenticate! => mock_current_user)
      setup_authorization
  end
  # endsnip
  
  def setup_authorization
    @ability = Object.new
    @ability.extend(CanCan::Ability)
    @controller.stub(:current_ability).and_return(@ability)
  end

  def mock_user(stubs={})
    @mock_user ||= mock_model(User, stubs).as_null_object
  end

  describe "GET index" do
    describe "authorized as admin" do
      it "assigns all admin_users as @admin_users" do
        @ability.can :manage, :all
        User.stub(:all) { [mock_user] }
        get :index
        assigns(:admin_users).should eq([mock_user])
      end
    end
    
    describe "not authorized as admin" do
      it "does not assign all admin_users as @admin_users" do
        should_not be_able_to(:view, :index)
      end
    end
  end

  describe "GET show" do
    describe "authorized as admin" do
      it "assigns the requested user as @user" do
        @ability.can :manage, :all
        User.stub(:find).with("37") { mock_user }
        get :show, :id => "37"
        assigns(:admin_user).should be(mock_user)
      end
    end
    
    describe "not authorized as admin" do
      it "does not assign the requested user as @user" do
        should_not be_able_to(:view, :show)
      end
    end
  end

  describe "GET new" do
    it "assigns a new user as @user" do
      @ability.can :manage, :all
      User.stub(:new) { mock_user }
      get :new
      assigns(:admin_user).should be(mock_user)
    end
  end

  describe "GET edit" do
    it "assigns the requested user as @user" do
      @ability.can :manage, :all
      User.stub(:find).with("37") { mock_user }
      get :edit, :id => "37"
      assigns(:admin_user).should be(mock_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user as @user" do
        @ability.can :manage, :all
        User.stub(:new).with({'these' => 'params'}) { mock_user(:save => true) }
        post :create, :user => {'these' => 'params'}
        assigns(:admin_user).should be(mock_user)
      end

      it "redirects to the created user" do
        @ability.can :manage, :all
        User.stub(:new) { mock_user(:save => true) }
        post :create, :user => {}
        response.should redirect_to(admin_user_url(mock_user))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        @ability.can :manage, :all
        User.stub(:new).with({'these' => 'params'}) { mock_user(:save => false) }
        post :create, :user => {'these' => 'params'}
        assigns(:admin_user).should be(mock_user)
      end

      it "re-renders the 'new' template" do
        @ability.can :manage, :all
        User.stub(:new) { mock_user(:save => false) }
        post :create, :user => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user" do
        @ability.can :manage, :all
        User.stub(:find).with("37") { mock_user }
        mock_user.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :user => {'these' => 'params'}
      end

      it "assigns the requested user as @user" do
        @ability.can :manage, :all
        User.stub(:find) { mock_user(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:admin_user).should be(mock_user)
      end

      it "redirects to the user" do
        @ability.can :manage, :all
        User.stub(:find) { mock_user(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(admin_user_url(mock_user))
      end
    end

    describe "with invalid params" do
      it "assigns the user as @user" do
        @ability.can :manage, :all
        User.stub(:find) { mock_user(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:admin_user).should be(mock_user)
      end

      it "re-renders the 'edit' template" do
        @ability.can :manage, :all
        User.stub(:find) { mock_user(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user" do
      @ability.can :manage, :all
      User.stub(:find).with("37") { mock_user }
      mock_user.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the admin_users list" do
      @ability.can :manage, :all
      User.stub(:find) { mock_user }
      delete :destroy, :id => "1"
      response.should redirect_to(admin_users_url)
    end
  end

end
